diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=rpushin
user.email=pushinruslan@gmail.com
gui.recentrepo=D:/Projects/Skillf/DS
gui.recentrepo=D:/Projects/Skillf/c5homework
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.c5homework.url=github
remote.c5homework.fetch=+refs/heads/*:refs/remotes/c5homework/*
gui.wmstate=normal
gui.geometry=893x435+182+182 175 196
remote.moduleC5_homework.url=git@github.com:rpushin/moduleC5_homework
remote.moduleC5_homework.fetch=+refs/heads/*:refs/remotes/moduleC5_homework/*
remote.origin.url=git@github.com:rpushin/moduleC5_homework.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
